#! /usr/bin/python
# -*- coding: utf8 -*-

from __future__ import unicode_literals

import LaTeXparser
import LaTeXparser.PytexTools
import commons
import plugins_agreg

myRequest = LaTeXparser.PytexTools.Request("futur")

myRequest.original_filename="mazhe.tex"

myRequest.ok_hash=commons.ok_hash
myRequest.ok_filenames_list.append("e_mazhe")
myRequest.ok_filenames_list.append("SystemeCoordOM")
myRequest.ok_filenames_list.append("calcul_differentiel")
myRequest.ok_filenames_list.append("plusieurs_variables")
myRequest.ok_filenames_list.append("champs_vecteurs")
myRequest.ok_filenames_list.append("curviligne")
myRequest.ok_filenames_list.append("integrales")
myRequest.ok_filenames_list.append("Stokes_et_co")
myRequest.ok_filenames_list.append("theorie_generale")
myRequest.ok_filenames_list.append("liste_exos_outils_math")
myRequest.ok_filenames_list.append("questionsMazhe")
myRequest.ok_filenames_list.append("app_statement")
myRequest.ok_filenames_list.append("categorie")
myRequest.ok_filenames_list.append("topo")
myRequest.ok_filenames_list.append("directedSets")
myRequest.ok_filenames_list.append("var_diff")
myRequest.ok_filenames_list.append("diff_geom")
myRequest.ok_filenames_list.append("Lie_gp_and_subgp")
myRequest.ok_filenames_list.append("0060_mazhe")
myRequest.ok_filenames_list.append("0061_mazhe")
myRequest.ok_filenames_list.append("0062_mazhe")
myRequest.ok_filenames_list.append("0063_mazhe")
myRequest.ok_filenames_list.append("0064_mazhe")
myRequest.ok_filenames_list.append("0065_helgaLie")
myRequest.ok_filenames_list.append("0410_fibre_bundle")
myRequest.ok_filenames_list.append("0411_fibre_bundle")
myRequest.ok_filenames_list.append("0070_iwasawa")
myRequest.ok_filenames_list.append("0076_mazhe")
myRequest.ok_filenames_list.append("0430_helga")
myRequest.ok_filenames_list.append("Mecanique")
myRequest.ok_filenames_list.append("algebroid")
myRequest.ok_filenames_list.append("Hilbert")
myRequest.ok_filenames_list.append("reprez_Lie_Hilbert")
myRequest.ok_filenames_list.append("anal_notations")
myRequest.ok_filenames_list.append("distrib")
myRequest.ok_filenames_list.append("Sobolev")
myRequest.ok_filenames_list.append("frechet")
myRequest.ok_filenames_list.append("garding")
myRequest.ok_filenames_list.append("app_oscilla")
myRequest.ok_filenames_list.append("Dixmier_tr")
myRequest.ok_filenames_list.append("0470_algebre")
myRequest.ok_filenames_list.append("0471_algebre")
myRequest.ok_filenames_list.append("Cyclic_homol")
myRequest.ok_filenames_list.append("chaines")
myRequest.ok_filenames_list.append("0440_homo")
myRequest.ok_filenames_list.append("0442_homo")
myRequest.ok_filenames_list.append("0441_homo")
myRequest.ok_filenames_list.append("chaleur")
myRequest.ok_filenames_list.append("0520_CliffordSpin")
myRequest.ok_filenames_list.append("0521_CliffordSpin")
myRequest.ok_filenames_list.append("MQ")
myRequest.ok_filenames_list.append("0530_Fibre_QFT")
myRequest.ok_filenames_list.append("0550_cstar")
myRequest.ok_filenames_list.append("0551_cstar")
myRequest.ok_filenames_list.append("0552_cstar")
myRequest.ok_filenames_list.append("compact_quantum_groups")
myRequest.ok_filenames_list.append("0560_VN_algebras")
myRequest.ok_filenames_list.append("0561_VN_algebras")
myRequest.ok_filenames_list.append("0562_VN_algebras")
myRequest.ok_filenames_list.append("0563_VN_algebras")
myRequest.ok_filenames_list.append("Dirichlet")
myRequest.ok_filenames_list.append("ktheory")
myRequest.ok_filenames_list.append("bf_theory")
myRequest.ok_filenames_list.append("PetiteDim")
myRequest.ok_filenames_list.append("oldBTZ")
myRequest.ok_filenames_list.append("BTZ_3")
myRequest.ok_filenames_list.append("introduction")
myRequest.ok_filenames_list.append("0610_BTZ")
myRequest.ok_filenames_list.append("0612_BTZ")
myRequest.ok_filenames_list.append("0611_BTZ")
myRequest.ok_filenames_list.append("0613_BTZ")
myRequest.ok_filenames_list.append("0523_DiracAdS")
myRequest.ok_filenames_list.append("0524_DiracAdS")
myRequest.ok_filenames_list.append("conclThese")
myRequest.ok_filenames_list.append("avecOld")
myRequest.ok_filenames_list.append("0640_noncommutative_geometry")
myRequest.ok_filenames_list.append("0641_noncommutative_geometry")
myRequest.ok_filenames_list.append("deformation_formal")
myRequest.ok_filenames_list.append("twists_general")
myRequest.ok_filenames_list.append("qansl")
myRequest.ok_filenames_list.append("KG")
myRequest.ok_filenames_list.append("universel")
myRequest.ok_filenames_list.append("deformation_AdS4")
myRequest.ok_filenames_list.append("axplusb")
myRequest.ok_filenames_list.append("unif_so2n")
myRequest.ok_filenames_list.append("NCgrav")
myRequest.ok_filenames_list.append("LevyProcess")
myRequest.ok_filenames_list.append("app_Wigner")
myRequest.ok_filenames_list.append("app_Maxima")
myRequest.ok_filenames_list.append("erreurs")
myRequest.ok_filenames_list.append("faq")
myRequest.ok_filenames_list.append("0720_matlab")
myRequest.ok_filenames_list.append("TD_SVT")
myRequest.ok_filenames_list.append("<++>")
myRequest.ok_filenames_list.append("<++>")
myRequest.ok_filenames_list.append("<++>")
